name: mow
description: Model -  Observer - Widget A simple state management solution for Flutter
version: 1.0.0
# homepage: https://www.example.com
publish_to: none #get rid of this

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  updatable:
    path: /Users/usuario/Documents/KC-BOOTCAMP-XII/flutter/KC/DAVID/updatable

  flutter:
    sdk: flutter

  meta: ^1.7.0

dev_dependencies:
  lint: ^1.0.0
  test: ^1.16.0
