# Defines a default set of lint rules enforced for projects at Google. For
# details and rationale, see
# https://github.com/dart-lang/pedantic#enabled-lints.

include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    no_runtimeType_toString: false 
    unrelated_type_equality_checks: false
    avoid_function_literals_in_foreach_calls: false
    
    

